upstream sorelle_frontend {
    server frontend:3000;
}

upstream sorelle_backend {
    server backend:3001;
}

# Loja — sorellepresentes.com.br
server {
    listen 80;
    server_name sorellepresentes.com.br www.sorellepresentes.com.br;

    client_max_body_size 15m;

    location / {
        proxy_pass http://sorelle_frontend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# API — api.sorellepresentes.com.br
server {
    listen 80;
    server_name api.sorellepresentes.com.br;

    client_max_body_size 15m;

    location / {
        proxy_pass http://sorelle_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
